initial_dir: initial_files
parmfile: mon.prmtop
trajfile: mon_prod.nc
ligand_mask: ":170"
protein_mask: ":1-169"
distance: 3.0
fraction: 0.5
contacts_txt: contacts.txt
fraction_txt: fraction.txt
resid_txt: resids.txt
